### ISSUE TITLE
Combined Pan & Volume 2D Control for Mixer UI

### ISSUE THREAD

**Issue by ericfont** [musescore/MuseScore_design#10]
I'm proposing a 3.0 idea to replace the Pan knob and the Volume knob in the mixer by merging them into a combined Two-Dimensional Pan & Volume control, which would look like:

![merged-volume-pan-mockup-2d-slider-at-peak](https://cloud.githubusercontent.com/assets/6502474/25312097/5ae925c0-27de-11e7-97f0-ad9b0fbafa2e.png)

The nice thing about using blue triangles to represent each gain is that improves communication because:
1. The size of each area is proportional to the gain of that instrument.
2. The horizontal position of its peak corresponds exactly to the pan level, such that a perfectly symmetrical isosceles triangle represents a balanced pan in the Center, while a hard pan will contain more of the triangle towards the Left or Right (which correlates to how much level is in the left or right channel).

The basic operation with the mouse is:
1. Dragging Left/Right will pan left/right.
2. Dragging Up/Down will increase/decrease gain.

Note: I think best to only control one axis at a time, such that is horizontal drag is greater than vertical drag, then will only control pan, while if vertical drag is greater than horizontal drag, then only control gain.

This two-dimensional control maps much better than a knob, especially on a labtop, mouse, or touchscreen.  And beyond basic operation controls:
1. Double clicking resets the level to default and resets pan to center (as is done currently).
2. Clicking on the "L" will set pan hard left, clicking "C" will set pan centered, clicking "R" will set pan hard right...this will allow easy one-click operations for setting L/C/R.
3. Left click (and not a drag) will set pan and gain according to the X and Y position of the mouse in the rectangular region.
4. MouseWheelUp in the rectangular region will increase gain by one notch, and MouseWheelDown will decrease gain by one notch.
5. Shift+MouseWheelUp will pan right a bit, and Shift+MouseWheelDown will pan left a bit.
6. Holding "Shift" while clicking will allow user to select multiple instruments, and then user can adjust gain or panning of all the selected instruments simultaneously by dragging left or right (or doing many of the other options).  I think this will help out tremendously for large scores when need to adjust lots of instruments at the same time.
Also, if an instrument is muted, then instead of a solid blue triangle, it will be an blue outline of a triangle with light grey inside.

Anyway, I'm proposing this in favor of #9, which I've closed.

**Comment by IsaacWeiss** [comment]
I would rather be able to control volume and panning entirely independently, as is currently possible, without even considering volume when I want to adjust panning and vice versa. Your note about sliding along one axis at a time sort of allows this, but still requires extra effort to separate the two mentally. That said, I realize your whole point in inventing this is the desire to have volume and panning no longer be thought of separately, so this may not be helpful feedback. 

A perhaps more specific visual problem with this design: when fully panned to right or left, the shaded area has maximum height at one edge and goes down to zero at the other, but at anything in between it appears to go to zero at both sides. Whether there's any way around this without introducing worse problems, I don't know.

**Comment by ericfont** [comment]
Thanks for your feedback.  You are probably right about this being too much mentally for average folk.  I should probably close this anyway, since it is something that has no chance of getting into musescore.  But I hope that the discussion will result in someone coming up with something better than the knobs for 3.0.

Your second comment is actually not really a problem. The panning effect causes the listener to perceive that the sound is somewhere in between left and right if not fully panned all the way left or right, so it actually sortof makes sense for there to be no shaded region when not panned all the way left or right.

**Comment by MikelNelson** [comment]
Not sure whether to comment on github or musescore.org...

On Isaac's point about the height going to zero. You (Eric) are right that the apex moves correctly, and it is acceptable. However, if a hard-right panned instrument moves an infinitesimal to the left, the value on the right side drops to zero, which to Isaac's point could be a little unsettling.

This raises the question, What is the meaning of the triangle? With a triangle in an intermediate position, i.e., the instrument panned somewhere between left and right, why is there zero at each side, yet non-zero half way between the side and the apex? I realize that you meant it just as a handy visual indicator, not as a full technical graph, but I'm just trying to dig into it. Back to your original diagram rather than the MS knob one above, and I'll suggest a variant on that.

Technically, a 1-dimensional vertical bar at each left/right side, showing the volume in each speaker, contains all the physical information. But we should not display it in this way, but rather depict it in the best way for our needs. Well, the perception is of the sound emanating from the intermediate point, so it is excessive to show two bars. I'm led to the conclusion that the proper display is not a triangle between the horizontal lines for an instrument, but a single (narrowish) column at the appropriate intermediate point between left and right, and nothing else between the lines. I think this display, if I have explained what I meant properly, retains your nice idea of vertical summation, and handles the display of panning decently.

**Comment by ericfont** [comment]
Ok, fair points.

"What is the meaning of the triangle?"
Well I switched to triangle-only because I realized my previous design #9 had triangles, trapezoids, and rectangles, and I realized that the triangle would be more consistant since the tip of the triangle would always correspond to the panning value.

But now after thinking of it, you're revised design of having a single vertical column with x-position at the panning value and with height equal to the gain will convey all the meaning necessary and be more concise...  Let my try to make a mockup...

**Comment by ericfont** [comment]
I'm closing this issue and reopening as issue #11, incorporating MikelNelson's comment about using single column.
